const cities = [
    {"countryId": 1,"cityId":1,"cityName":"Canillo","iataCode": null,},
    {"countryId": 1,"cityId":2,"cityName":"L'Aldosa","iataCode": null},	
    {"countryId": 1,"cityId":3,"cityName":"L'Armiana","iataCode": null},
    {"countryId": 1,"cityId":4,"cityName":"Bordes d'Envalira","iataCode": null},
    {"countryId": 1,"cityId":5,"cityName":"El Forn","iataCode": null},
    {"countryId": 1,"cityId":6,"cityName":"Incles","iataCode": null},
    {"countryId": 1,"cityId":7,"cityName":"Meritxell","iataCode": null},
    {"countryId": 1,"cityId":8,"cityName":"Molleres","iataCode": null},
    {"countryId": 1,"cityId":9,"cityName":"Els Plans","iataCode": null},
    {"countryId": 1,"cityId":10,"cityName":"Prats","iataCode": null},
    {"countryId": 1,"cityId":11,"cityName":"Ransol","iataCode": null},
    {"countryId": 1,"cityId":12,"cityName":"Sant Pere","iataCode": null},
    {"countryId": 1,"cityId":13,"cityName":"Soldeu","iataCode": null},
    {"countryId": 1,"cityId":14,"cityName":"El Tarter","iataCode": null},
    {"countryId": 1,"cityId":15,"cityName":"El Vilar","iataCode": null},
    {"countryId": 1,"cityId":16,"cityName":"Encamp Encamp","iataCode": null},
    {"countryId": 1,"cityId":17,"cityName":"MLes Bons","iataCode": null},
    {"countryId": 1,"cityId":18,"cityName":"Grau Roig","iataCode": null},
    {"countryId": 1,"cityId":19,"cityName":"La Mosquera","iataCode": null},
    {"countryId": 1,"cityId":20,"cityName":"Pas de la Casa","iataCode": null},   
    {"countryId": 1,"cityId":21,"cityName":"Le Tremat","iataCode": null},   
    {"countryId": 1,"cityId":22,"cityName":"Vila","iataCode": null},      
    {"countryId": 1,"cityId":23,"cityName":"Ordino	Ordino","iataCode": null},   
    {"countryId": 1,"cityId":24,"cityName":"Ansalonga","iataCode": null}, 
    {"countryId": 1,"cityId":25,"cityName":"Arcalís","iataCode": null}, 
    {"countryId": 1,"cityId":26,"cityName":"Arans","iataCode": null}, 
    {"countryId": 1,"cityId":27,"cityName":"La Cortinada","iataCode": null}, 
    {"countryId": 1,"cityId":28,"cityName":"Llorts","iataCode": null}, 
    {"countryId": 1,"cityId":29,"cityName":"Les Salines","iataCode": null}, 
    {"countryId": 1,"cityId":30,"cityName":"Segudet","iataCode": null}, 
    {"countryId": 1,"cityId":31,"cityName":"El Serrat","iataCode": null}, 
    {"countryId": 1,"cityId":32,"cityName":"Sornàs","iataCode": null}, 
    {"countryId": 1,"cityId":33,"cityName":"La Massana	La Massana","iataCode": null}, 
    {"countryId": 1,"cityId":34,"cityName":"L'Aldosa","iataCode": null}, 
    {"countryId": 1,"cityId":35,"cityName":"Anyós","iataCode": null}, 
    {"countryId": 1,"cityId":36,"cityName":"Arinsal","iataCode": null}, 
    {"countryId": 1,"cityId":37,"cityName":"Erts","iataCode": null}, 
    {"countryId": 1,"cityId":38,"cityName":"Escàs","iataCode": null}, 
    {"countryId": 1,"cityId":39,"cityName":"Mas de Ribafeta","iataCode": null}, 
    {"countryId": 1,"cityId":40,"cityName":"Pal","iataCode": null}, 
    {"countryId": 1,"cityId":41,"cityName":"El Pui","iataCode": null}, 
    {"countryId": 1,"cityId":42,"cityName":"Puiol del Piu","iataCode": null}, 
    {"countryId": 1,"cityId":43,"cityName":"Sispony","iataCode": null}, 
    {"countryId": 1,"cityId":44,"cityName":"Xixerella","iataCode": null}, 
    {"countryId": 1,"cityId":45,"cityName":"Andorra la Vella","iataCode": null}, 
    {"countryId": 1,"cityId":46,"cityName":"La Margineda","iataCode": null}, 
    {"countryId": 1,"cityId":47,"cityName":"Santa Coloma","iataCode": null}, 
    {"countryId": 1,"cityId":48,"cityName":"Sant Julià de Lòria","iataCode": null}, 
    {"countryId": 1,"cityId":49,"cityName":"Aixàs","iataCode": null}, 
    {"countryId": 1,"cityId":50,"cityName":"Aixirivall","iataCode": null}, 
    {"countryId": 1,"cityId":51,"cityName":"Aixovall","iataCode": null}, 
    {"countryId": 1,"cityId":52,"cityName":"Auvinyà","iataCode": null}, 
    {"countryId": 1,"cityId":53,"cityName":"Bixessarri","iataCode": null}, 
    {"countryId": 1,"cityId":54,"cityName":"Canolich","iataCode": null}, 
    {"countryId": 1,"cityId":55,"cityName":"Certers","iataCode": null}, 
    {"countryId": 1,"cityId":56,"cityName":"Fontaneda","iataCode": null}, 
    {"countryId": 1,"cityId":57,"cityName":"Juberri","iataCode": null}, 
    {"countryId": 1,"cityId":58,"cityName":"Llumeneres","iataCode": null}, 
    {"countryId": 1,"cityId":59,"cityName":"Nagol","iataCode": null},    
    {"countryId": 1,"cityId":60,"cityName":"Escaldes-Engordany","iataCode": null}, 
    {"countryId": 1,"cityId":61,"cityName":"Engolasters","iataCode": null}, 
    {"countryId": 1,"cityId":62,"cityName":"El Fener","iataCode": null}, 
    {"countryId": 1,"cityId":63,"cityName":"NEls Vilars d'Engordany","iataCode": null},    	   
]

module.export = cities;